owner: fletec
repo: fletec-upptime

sites:
  - name: FLETEC Portal
    url: https://portal.fletec.io
    expectedStatusCodes:
      - 200
      - 401
  - name: FLETEC API
    url: https://api.fletec.io
  - name: FLETEC Documentation
    url: https://docs.fletec.io
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  cname: status.fletec.io
  logoUrl: https://raw.githubusercontent.com/fletec/fletec-upptime/master/assets/fletec.svg
  name: FLETEC Status
  introTitle: "**FLETEC** container M&R analytics platform"
  introMessage: This is FLETEC's real-time status page.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://fletec.io/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"